version: "3.2"
services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      DB_SERVICE: ${DB_SERVICE}
      DB_PORT: ${DB_PORT}
      SECRET_KEY: ${SECRET_KEY}

  adminer:
    image: adminer
    restart: always
    expose:
      # Change the value in the nginx configuration if this is changed
      - "8080"
    depends_on:
      - postgres

  web:
    restart: always
    build: ./web
    expose:
      # Change the value in the nginx configuration if this is changed
      - "8000"
    depends_on:
      - postgres
    env_file: .env
    environment:
      DB_SERVICE: ${DB_SERVICE}
      DB_PORT: ${DB_PORT}
      SECRET_KEY: ${SECRET_KEY}
      # Define this in .env for development mode. DO NOT USE IN PRODUCTION
      DEBUG: ${DEBUG}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_PORT: ${MAIL_PORT}
      ERROR_EMAIL: ${ERROR_EMAIL}

  nginx-errorreports:
    restart: always
    build: ./nginx/
    env_file: .env
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ./webdata:/usr/src/app
    networks:
      - default
      - nginx_net

networks:
  nginx_net:
    external: true
