#!/bin/bash
URL="http://127.0.0.1:8000/api/usage"

num_lines=$(wc -l ${1})
num_lines=$(echo ${num_lines} | awk '{print $1}')

if [ ${num_lines} -le 1 ]; then
  echo "preprocessing file"
  sed -i -r s/^\.+\\[// ${1}
  sed -i -r s/\\]\.+$/\\n/ ${1}
  sed -i s/\},\ /}\\n/g ${1}
  sed -i s/,\ /,/g ${1}
  sed -i s/:\ /:/g ${1}
  # database can create new unique url
  sed -i -r s_\"url\":\"http://reports.mantidproject.org/api/usage/[0-9]+/\",__g ${1}
  # remove unspecified optional parameters
  sed -i s/\"application\":\"\",//g ${1}
  sed -i s/\"component\":\"\",//g ${1}
  sed -i s/\"osReadable\":\"\",//g ${1}
fi

echo "sending documents"
while read json; do
  echo "$json"
  curl -H "Content-Type: application/json" ${URL} -d "$json"
  echo
done < ${1}
