# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-26 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_added_contact_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.CharField(help_text='user provided email', max_length=128),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='name',
            field=models.CharField(help_text='user provided name', max_length=128),
        ),
    ]
