# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-11 12:14
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_add_free_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileHash', models.CharField(default='', help_text='md5 name of recovery file', max_length=32)),
                ('fileStore', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/usr/src/app/recovery'), upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='errorreport',
            name='recoveryFile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.RecoveryFiles'),
        ),
    ]
