# Generated by Django 3.2.23 on 2024-04-15 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0007_add_issue_number_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="GithubIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "repoName",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="'user/repo_name': for example 'mantidproject/mantid'",
                        max_length=200,
                    ),
                ),
                (
                    "issueNumber",
                    models.CharField(blank=True, default="", max_length=16),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="errorreport",
            name="githubIssueNumber",
        ),
        migrations.AddField(
            model_name="errorreport",
            name="githubIssue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="services.githubissue",
            ),
        ),
    ]
