# Generated by Django 3.2.25 on 2024-11-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_add_github_issue_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorreport',
            name='cppCompressedTraces',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
