# Generated by Django 3.2.25 on 2024-12-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_errorreport_cppcompressedtraces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorreport',
            name='mantidVersion',
            field=models.CharField(max_length=64),
        ),
    ]