name: CI - Ubuntu

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  webtests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          architecture: x64
      - name: Checkout head
        uses: actions/checkout@v4
      - name: Run webtests
        run: bash ./run_web_tests.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          architecture: x64
      - name: Checkout head
        uses: actions/checkout@v4
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: cd web && flake8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
